apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ../infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: notlazymisha/auth
      context: ../auth-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: notlazymisha/client
      context: ../client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
